Feature/removebg (#2)
* feat: 백그라운드 이미지 삭제 컴포넌트

* feat: add docker server

* error: 파일 업로드

* fix: 파일 업로드 수정

* feat: feat: improve background removal performance

* chore: delete logging

* deploy: add u2net image processor

* design: 이미지 업로드 컴포넌트 디자인 변경
error: 백그라운드 결과값 가져오기 에러

* fass

* refacor: 파일 세이버 사용

* feat: 백그라운드 지워진 이미지 가져오기 완료
error: 파일 드래그 앤 드랍 && 업로드 버튼 액션 수정 필요

* feat: remove bg with url

* feat: improve img quality

* feat: 이미지 파일 업로드 && 결과 이미지 다운로드 컴포넌트 완료

* refactor: seperate img app and docx app

* refactor: img server refactor

* feat: pdf server init

* feat: pdf to docx

* fix: TypeError: a bytes-like object is required, not '_io.BytesIO'

* feat: GET URL 이미지 파일 데이터

* refactor: Upload 버튼 액션 수정

* fix: delete post process

* chore: 서버 분리 적용

---------

Co-authored-by: minkj1992 <minkj1992@gmail.com>